[project]
name = "epsilongreedy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ 
    "numpy >=1.22.0",
    "scipy >=1.8.0",
    "matplotlib >=3.5.0",
    "apyori >=1.1.2",
    "pandas >=1.3.0",
    "pyfim >=6.28"
    ]
